(function() {

  var TERMS = [
    {
      match: ['fossil fuels', 'fossil fuel', 'coal', 'oil and gas'],
      term: 'Fossil Fuels',
      nickname: '"Dinosaur Juice"',
      def: 'Non-renewable energy from ancient remains of plants and animals (Coal, Oil, Gas). Burning them makes the Earth sick.'
    },
    {
      match: ['renewable energy', 'renewables', 'clean energy'],
      term: 'Renewable Energy',
      nickname: '"Infinite Magic Power"',
      def: 'Energy from sources that naturally replenish themselves — sun, wind, water. They never run out and make no smoke.'
    },
    {
      match: ['energy transition'],
      term: 'Energy Transition',
      nickname: 'The Big Diet Change',
      def: 'Switching our countries from fossil fuels (junk food) to clean, renewable energy (superfoods) for everyone.'
    },
    {
      match: ['carbon footprint'],
      term: 'Carbon Footprint',
      nickname: '"Your Invisible Shadow"',
      def: 'The total greenhouse gases generated by your actions. Every car trip or plastic purchase leaves a mark. We want to make it smaller.'
    },
    {
      match: ['carbon offsetting', 'carbon offset', 'offsets'],
      term: 'Carbon Offsetting',
      nickname: '"Paying for Chores"',
      def: 'Compensating for your emissions by funding equivalent carbon savings elsewhere. Helpful — but your room is still messy.'
    },
    {
      match: ['net zero'],
      term: 'Net Zero',
      nickname: '"The Bathtub Rule"',
      def: 'Balancing the greenhouse gases put into the atmosphere with those taken out. Turn off the tap or open the drain — don\'t let it overflow.'
    },
    {
      match: ['greenhouse gas', 'greenhouse gases', 'ghg', 'co2', 'carbon dioxide', 'methane'],
      term: 'Greenhouse Gases',
      nickname: '"A Heavy Blanket"',
      def: 'Gases like CO₂ and methane that trap heat in the atmosphere. The more we pump out, the thicker the blanket — and the more Earth sweats.'
    },
    {
      match: ['greenwashing'],
      term: 'Greenwashing',
      nickname: '"Faking It"',
      def: 'Deceptive marketing that makes a company seem eco-friendly when it isn\'t. Like calling a cookie a salad because the wrapper is green.'
    },
    {
      match: ['just transition'],
      term: 'Just Transition',
      nickname: '"Moving House Together"',
      def: 'Greening the economy in a way that\'s fair to all workers and communities. We can\'t leave coal workers behind — we help them pack and move too.'
    },
    {
      match: ['climate justice'],
      term: 'Climate Justice',
      nickname: '"Fair Play"',
      def: 'Those who did the least to cause climate change suffer the most. Climate justice means making the rules fair for everyone.'
    },
    {
      match: ['decarbonisation', 'decarbonization', 'decarbonise', 'decarbonize'],
      term: 'Decarbonisation',
      nickname: '"Going on a Diet"',
      def: 'Reducing or removing carbon emissions from an economy or sector. Cutting the junk food (carbon) out of our daily lives to get healthy.'
    },
    {
      match: ['energy efficiency'],
      term: 'Energy Efficiency',
      nickname: '"Sipping Slowly"',
      def: 'Using less energy to do the same task. Same fun from your juice box — just making it last longer.'
    },
    {
      match: ['tipping point', 'tipping points'],
      term: 'Tipping Point',
      nickname: '"The Jenga Tower"',
      def: 'A threshold that, when crossed, causes large irreversible changes. Pull one wrong block and the whole tower crashes — you can\'t put it back.'
    },
    {
      match: ['loss and damage'],
      term: 'Loss and Damage',
      nickname: '"You Break It, You Buy It"',
      def: 'Climate impacts that can\'t be avoided or adapted to — like land lost to rising seas. Big countries broke the climate. They should pay for the damage.'
    },
    {
      match: ['adaptation', 'adapt'],
      term: 'Adaptation',
      nickname: '"Buying an Umbrella"',
      def: 'Adjusting to climate change that\'s already happening. The rain is here — we need to learn how to stay dry.'
    },
    {
      match: ['mitigation'],
      term: 'Mitigation',
      nickname: '"Stop the Leak"',
      def: 'Actions that reduce or prevent greenhouse gas emissions. Fix the hole in the roof so the rain stops coming in.'
    },
    {
      match: ['solar energy', 'solar power', 'rooftop solar', 'floating solar'],
      term: 'Solar Energy',
      nickname: 'The People\'s Champ',
      def: 'Energy from the sun. The cheapest new electricity in history — and we have sun year-round in Southeast Asia.'
    },
    {
      match: ['geothermal'],
      term: 'Geothermal Energy',
      nickname: 'Volcano Power',
      def: 'Heat from under the earth. Indonesia and the Philippines are world leaders because of the Ring of Fire.'
    },
    {
      match: ['circular economy'],
      term: 'Circular Economy',
      nickname: '"Legos"',
      def: 'Reusing, repairing, and recycling materials as long as possible. Like taking apart a Lego castle and building a spaceship — no waste.'
    },
    {
      match: ['esg'],
      term: 'ESG',
      nickname: '"A Company Report Card"',
      def: 'Environmental, Social, and Governance standards. Not just how much money a company makes — but if they\'re being good to people and the planet.'
    },
    {
      match: ['global boiling'],
      term: 'Global Boiling',
      nickname: '"It\'s Not Just Warm — It\'s Cooking"',
      def: 'A term coined by the UN because "global warming" wasn\'t strong enough. Imagine leaving a pot of soup on the stove too long. That\'s us right now.'
    },
    {
      match: ['1.5°c', '1.5 degrees', '1.5°'],
      term: '1.5°C Target',
      nickname: '"The Safety Line"',
      def: 'The goal to limit global temperature rise to 1.5°C above pre-industrial levels. Like a body temperature — go too high and the planet goes to hospital.'
    }
  ];

  /* Build a fast lookup map: lowercase phrase → term object */
  var lookup = {};
  TERMS.forEach(function(t) {
    t.match.forEach(function(m) { lookup[m.toLowerCase()] = t; });
  });

  /* Sort phrases longest-first so "carbon footprint" matches before "carbon" */
  var phrases = Object.keys(lookup).sort(function(a,b){ return b.length - a.length; });

  /* ---- Tooltip element ---- */
  var tip = document.createElement('div');
  tip.id = 'gtip';
  tip.style.cssText = [
    'position:fixed',
    'z-index:9999',
    'max-width:260px',
    'background:#072d1c',
    'border-radius:10px',
    'padding:10px 13px',
    'pointer-events:none',
    'opacity:0',
    'transition:opacity .15s',
    'font-family:Raleway,sans-serif'
  ].join(';');
  tip.innerHTML = '<div id="gtip-nick" style="font-size:11px;font-weight:700;color:#fb8b24;margin-bottom:3px"></div>'
                + '<div id="gtip-term" style="font-size:12px;font-weight:800;color:#fff;margin-bottom:5px"></div>'
                + '<div id="gtip-def" style="font-size:12px;color:rgba(255,255,255,.8);line-height:1.55"></div>'
                + '<div style="font-size:10px;color:rgba(255,255,255,.4);margin-top:6px;font-weight:600">📝 See full glossary</div>';

  document.body.appendChild(tip);

  /* ---- Inject CSS underline style ---- */
  var style = document.createElement('style');
  style.textContent = '.gterm{border-bottom:1.5px dotted #fb8b24;cursor:help;color:inherit}';
  document.head.appendChild(style);

  /* ---- Walk text nodes and wrap matches ---- */
  function escapeReg(s){ return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); }

  var pattern = new RegExp('\\b(' + phrases.map(escapeReg).join('|') + ')\\b', 'gi');

  function walkNode(node) {
    /* Skip scripts, styles, existing tooltips, links, headings */
    if (!node) return;
    var skip = ['SCRIPT','STYLE','A','H1','NAV','BUTTON'];
    if (node.nodeType === 1) {
      if (skip.indexOf(node.tagName) > -1) return;
      if (node.classList && node.classList.contains('gterm')) return;
      Array.from(node.childNodes).forEach(walkNode);
      return;
    }
    if (node.nodeType !== 3) return;
    var text = node.nodeValue;
    if (!pattern.test(text)) return;
    pattern.lastIndex = 0;

    var frag = document.createDocumentFragment();
    var last = 0, m;
    pattern.lastIndex = 0;
    while ((m = pattern.exec(text)) !== null) {
      var key = m[0].toLowerCase();
      var tObj = lookup[key];
      if (!tObj) continue;
      if (m.index > last) frag.appendChild(document.createTextNode(text.slice(last, m.index)));
      var span = document.createElement('span');
      span.className = 'gterm';
      span.textContent = m[0];
      span.dataset.tterm = tObj.term;
      span.dataset.tnick = tObj.nickname;
      span.dataset.tdef = tObj.def;
      frag.appendChild(span);
      last = m.index + m[0].length;
    }
    if (last < text.length) frag.appendChild(document.createTextNode(text.slice(last)));
    if (frag.childNodes.length > 1) node.parentNode.replaceChild(frag, node);
  }

  /* ---- Show / hide tooltip ---- */
  var hideTimer;

  function showTip(e) {
    clearTimeout(hideTimer);
    var el = e.currentTarget;
    document.getElementById('gtip-term').textContent = el.dataset.tterm;
    document.getElementById('gtip-nick').textContent = el.dataset.tnick;
    document.getElementById('gtip-def').textContent = el.dataset.tdef;

    var rect = el.getBoundingClientRect();
    var tx = rect.left;
    var ty = rect.top - 10;

    /* flip up/down */
    if (ty - 130 < 0) ty = rect.bottom + 10;
    else ty = ty - 130;

    /* clamp horizontally */
    tx = Math.min(tx, window.innerWidth - 275);
    tx = Math.max(tx, 8);

    tip.style.left = tx + 'px';
    tip.style.top = ty + 'px';
    tip.style.opacity = '1';
  }

  function hideTip() {
    hideTimer = setTimeout(function(){ tip.style.opacity = '0'; }, 120);
  }

  /* ---- Init after DOM ready ---- */
  function init() {
    var content = document.querySelector('body');
    walkNode(content);

    document.querySelectorAll('.gterm').forEach(function(el) {
      el.addEventListener('mouseenter', showTip);
      el.addEventListener('mouseleave', hideTip);
      el.addEventListener('touchstart', showTip, {passive:true});
      el.addEventListener('touchend', hideTip);
      el.addEventListener('click', function(e) {
        e.preventDefault();
        window.location.href = 'kol-l1-glossary.html';
      });
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
